---
version: "1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /path/to/config:/config
      - /path/to/tvseries:/tv
      - /path/to/movies:/movies
    restart: unless-stopped