services:
  mealie:
    image: hkotel/mealie:latest
    container_name: mealie
    ports:
      - "9925:9000"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - BASE_URL=${BASE_URL}
    volumes:
      - ./mealie-data:/app/data
    restart: unless-stopped
