version: '3.8'

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:latest
    container_name: immich-server
    ports:
      - "2283:3001"
    environment:
      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
      DB_USERNAME: ${IMMICH_DB_USER}
      DB_DATABASE_NAME: ${IMMICH_DB_NAME}
      REDIS_HOSTNAME: immich-redis
      DB_HOSTNAME: immich-db
    volumes:
      - ./photos:/usr/src/app/upload
    depends_on:
      - immich-db
      - immich-redis

  immich-db:
    image: postgres:14
    container_name: immich-db
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: ${IMMICH_DB_USER}
      POSTGRES_DB: ${IMMICH_DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  immich-redis:
    image: redis:alpine
    container_name: immich-redis
