---
version: '1'
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.6.0
    container_name: mealie
    restart: always
    ports:
      - "30041:30041"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - immich-data:/app/data/
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=http://192.168.1.8:30041 # Adjust this to your actual base URL
volumes:
  mealie-data: